const exerciseList = {
  bodyweight: [
    "Push-ups",
    "Squats",
    "Lunges",
    "Burpees",
    "Mountain climbers",
    "Pull-ups/Chin-ups",
    "Dips",
    "Russian twists",
    "Glute bridge",
    "Pike push-ups",
    "Inverted rows",
    "Superman",
    "Hyperextensions",
    "Hanging leg raises",
  ],
  dumbbell: [
    "Goblet squats",
    "Romanian deadlifts",
    "Chest press",
    "Shoulder press",
    "Bicep curls",
    "Lateral raises",
    "Bent-over rows",
    "Farmer's walks",
    "Calf raises",
  ],
  balance: [
    "Single-leg stand",
    "Single-leg deadlift",
    "Plank with alternating leg lift",
    "Bosu ball squats",
  ],
  core: ["Ab wheel rollouts", "Pallof press"],
  stretching: [
    "Standing forward bend",
    "Lunge with spinal twist",
    "Cat-cow stretch",
    "Downward facing dog",
    "Pigeon pose",
    "Child's pose",
    "Cobra stretch",
    "World's greatest stretch",
    "Hip flexor stretch",
    "Hamstring stretch",
    "Doorway chest stretch",
    "Arm circles",
  ],
  cardio: [
    "High knees",
    "Jump rope",
    "Squat jumps",
    "Running",
    "Rowing",
    "Step climber",
  ],
};
