const exerciseList = {
  bodyweight: [
    "Push-ups",
    "Squats",
    "Lunges",
    "Burpees",
    "Plank",
    "Mountain climbers",
    "Pull-ups/Chin-ups",
    "Dips",
    "Jump squats",
    "Russian twists",
    "Glute bridge",
    "Pike push-ups",
    "Inverted rows",
    "Superman",
    "Hyperextensions",
  ],
  dumbbell: [
    "Goblet squats",
    "Romanian deadlifts",
    "Renegade rows",
    "Chest press",
    "Shoulder press",
    "Bicep curls",
    "Tricep extensions",
    "Lateral raises",
    "Lunges with dumbbells",
    "Bent-over rows",
    "Farmer's walks",
    "Dumbbell squat to press",
    "Calf Raises",
    "Single-arm Dumbbell Row",
  ],
  balance: [
    "Single-leg stand",
    "Bosu ball squats",
    "Walking lunges",
    "Single-leg deadlift",
    "Plank with alternating leg lift",
  ],
  stretching: [
    "Standing forward bend",
    "Lunge with spinal twist",
    "Cat-cow stretch",
    "Downward facing dog",
    "Pigeon pose",
    "Child's pose",
    "Cobra stretch",
    "Butterfly stretch",
    "World's greatest stretch",
    "Side lunges",
  ],
  cardio: [
    "High knees",
    "Jumping jacks",
    "Burpees",
    "Jump rope",
    "Squat jumps",
    "Mountain climbers",
  ],
};
